name: CI
on: [push, pull_request]
jobs:
    linux-ci:
        name: Linux
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Release
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Debug

                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Release
                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Debug

                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Release
                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Debug

                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Release
                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Debug

                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Release
                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                sudo apt-get install -o APT::Install-Recommends=false -o APT::Install-Suggests=false -y libuhd-dev
                cd ${{runner.workspace}}

                # Build against earliest supported SoapySDR
                git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.6.0
                mkdir SoapySDR/build
                cd SoapySDR/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF ..
                make
                sudo make install
                sudo ldconfig
          - name: Build SoapyUHD
            run: |
                mkdir ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
          - name: Test module registration
            run: |
                SoapySDRUtil --check=uhd
    osx-ci:
        name: OS X
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: clang
                      cxx: clang++
                      build_type: Release
                    - cc: clang
                      cxx: clang++
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                brew install uhd
                cd ${{runner.workspace}}

                # Build against earliest supported SoapySDR
                git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.6.0
                mkdir SoapySDR/build
                cd SoapySDR/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF ..
                make
                sudo make install
          - name: Build SoapyUHD
            run: |
                mkdir ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
          - name: Test module registration
            run: |
                SoapySDRUtil --check=uhd
    windows-ci:
        name: Windows
        runs-on: windows-2019
        strategy:
            fail-fast: false
            matrix:
                # Note: keeping cmake_config general enough for non-MSVC later
                include:
                      # Note: skipping VS2017, possible bugginess in parallel installs

                    - cmake_config: -G "Visual Studio 16 2019" -A "Win32"
                      arch: win32
                      build_type: Release
                      uhd_vs_version: 2019
                      uhd_arch: x86

                    - cmake_config: -G "Visual Studio 16 2019" -A "Win32"
                      arch: win32
                      build_type: Debug
                      uhd_vs_version: 2019
                      uhd_arch: x86

                    - cmake_config: -G "Visual Studio 16 2019" -A "x64"
                      arch: x64
                      build_type: Release
                      uhd_vs_version: 2019
                      uhd_arch: x64

                    - cmake_config: -G "Visual Studio 16 2019" -A "x64"
                      arch: x64
                      build_type: Debug
                      uhd_vs_version: 2019
                      uhd_arch: x64
        env:
            # Easier to have multiple copies of a subpath than deal with CI path parsing issues
            INSTALL_PREFIX: 'C:\Program Files\SoapySDR'
            UHD_VERSION: 4.1.0.4
            UHD_PREFIX: 'C:\Program Files\UHD'
        steps:
          - uses: actions/checkout@v2
          - uses: ilammy/msvc-dev-cmd@v1
            with:
                arch: ${{matrix.arch}}
          - name: Download and build Boost # TODO: cache
            uses: egor-tensin/build-boost@v1
            with:
                version: 1.70.0 # Matches UHD installer
                libraries: thread system
                platform: x64
                configuration: Release
          - name: Download and install UHD # TODO: cache
            run: |
                # No minimum UHD version, so just install a reasonably recent version
                cd ${{runner.workspace}}
                $Env:UHD_INSTALLER = "https://files.ettus.com/binaries/uhd/latest_release/" + $Env:UHD_VERSION + "/Windows-10-x64/uhd_" + $Env:UHD_VERSION + "-release_Win${{matrix.uhd_arch}}_VS${{matrix.uhd_vs_version}}.exe"
                echo "Downloading " + $Env:UHD_INSTALLER
                Invoke-WebRequest $Env:UHD_INSTALLER -OutFile uhd_installer.exe
                7z x uhd_installer.exe -o'$Env:UHD_PREFIX' -bd
          - name: Download and build SoapySDR
            run: |
                # Build against earliest supported SoapySDR
                git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.6.0
                mkdir SoapySDR\build
                cd SoapySDR\build
                cmake ${{matrix.cmake_config}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..
                cmake --build . --config ${{matrix.build_type}}
                cmake --install . --config ${{matrix.build_type}}
